safe: true
pygments: true
lsi: false
permalink: /:categories/:title
url: https://ryanseys.com
markdown: maruku
port: 4000
future: false
exclude:
- README.md
- CNAME
- params.json
- Gemfile
- Gemfile.lock
include:
- .well-known
